//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabi.LeBibi.Business.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabi.LeBibi.Business.Resource.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário {0} não tem permissão de acesso à funcionalidade {1}.
        /// </summary>
        internal static string Autenticacao_AcessoNegado {
            get {
                return ResourceManager.GetString("Autenticacao_AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login expirado, faça a autenticação novamente.
        /// </summary>
        internal static string Autenticacao_LoginExpirado {
            get {
                return ResourceManager.GetString("Autenticacao_LoginExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário autenticação.
        /// </summary>
        internal static string Autenticacao_NecessarioAutenticacao {
            get {
                return ResourceManager.GetString("Autenticacao_NecessarioAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao enviar email id {0}. {1}.
        /// </summary>
        internal static string Email_ErroEnvio {
            get {
                return ResourceManager.GetString("Email_ErroEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email salvo com sucesso.
        /// </summary>
        internal static string Email_SalvaEmailOK {
            get {
                return ResourceManager.GetString("Email_SalvaEmailOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidade excluída com sucesso.
        /// </summary>
        internal static string Funcionalidade_ExcluiFuncionalidadeOK {
            get {
                return ResourceManager.GetString("Funcionalidade_ExcluiFuncionalidadeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A funcionalidade não pode ser excluída pois está associada a um perfil ou tem uma funcionalidade filho.
        /// </summary>
        internal static string Funcionalidade_FuncionalidadeUtilizada {
            get {
                return ResourceManager.GetString("Funcionalidade_FuncionalidadeUtilizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidade salva com sucesso.
        /// </summary>
        internal static string Funcionalidade_SalvaFuncionalidadeOK {
            get {
                return ResourceManager.GetString("Funcionalidade_SalvaFuncionalidadeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil não pode ser excluído pois está associado a um usuário.
        /// </summary>
        internal static string Perfil_CadastroUtilizado {
            get {
                return ResourceManager.GetString("Perfil_CadastroUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil excluído com sucesso.
        /// </summary>
        internal static string Perfil_ExcluiPerfilOK {
            get {
                return ResourceManager.GetString("Perfil_ExcluiPerfilOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil não encontrado.
        /// </summary>
        internal static string Perfil_NaoEncontrado {
            get {
                return ResourceManager.GetString("Perfil_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        internal static string Perfil_Nome {
            get {
                return ResourceManager.GetString("Perfil_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil salvo com sucesso.
        /// </summary>
        internal static string Perfil_SalvaPerfilOK {
            get {
                return ResourceManager.GetString("Perfil_SalvaPerfilOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil não pode ser editado nem excluído.
        /// </summary>
        internal static string Perfil_SemPermissaoEdicaoExclusao {
            get {
                return ResourceManager.GetString("Perfil_SemPermissaoEdicaoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilFuncionalidade excluído com sucesso.
        /// </summary>
        internal static string PerfilFuncionalidade_ExcluiAcessoOK {
            get {
                return ResourceManager.GetString("PerfilFuncionalidade_ExcluiAcessoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilFuncionalidade não encontrado.
        /// </summary>
        internal static string PerfilFuncionalidade_NaoEncontrado {
            get {
                return ResourceManager.GetString("PerfilFuncionalidade_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilFuncionalidade salvo com sucesso.
        /// </summary>
        internal static string PerfilFuncionalidade_SalvaAcessoOK {
            get {
                return ResourceManager.GetString("PerfilFuncionalidade_SalvaAcessoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilUsuario excluído com sucesso.
        /// </summary>
        internal static string PerfilUsuario_ExcluiPerfilUsuarioOK {
            get {
                return ResourceManager.GetString("PerfilUsuario_ExcluiPerfilUsuarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilUsuario não encontrado.
        /// </summary>
        internal static string PerfilUsuario_NaoEncontrado {
            get {
                return ResourceManager.GetString("PerfilUsuario_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilUsuario salvo com sucesso.
        /// </summary>
        internal static string PerfilUsuario_SalvaPerfilUsuarioOK {
            get {
                return ResourceManager.GetString("PerfilUsuario_SalvaPerfilUsuarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um produto com o código informado.
        /// </summary>
        internal static string Produto_CadastroDuplicado {
            get {
                return ResourceManager.GetString("Produto_CadastroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo código é obrigatório.
        /// </summary>
        internal static string Produto_Codigo {
            get {
                return ResourceManager.GetString("Produto_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo descrição é obrigatório.
        /// </summary>
        internal static string Produto_Descricao {
            get {
                return ResourceManager.GetString("Produto_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto excluído com sucesso.
        /// </summary>
        internal static string Produto_ExcluiProdutoOK {
            get {
                return ResourceManager.GetString("Produto_ExcluiProdutoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo margem lucro é obrigatório.
        /// </summary>
        internal static string Produto_MargemLucro {
            get {
                return ResourceManager.GetString("Produto_MargemLucro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto não encontrado.
        /// </summary>
        internal static string Produto_NaoEncontrado {
            get {
                return ResourceManager.GetString("Produto_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo quantidade é obrigatório.
        /// </summary>
        internal static string Produto_Quantidade {
            get {
                return ResourceManager.GetString("Produto_Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto salvo com sucesso.
        /// </summary>
        internal static string Produto_SalvaProdutoOK {
            get {
                return ResourceManager.GetString("Produto_SalvaProdutoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo valor compra é obrigatório.
        /// </summary>
        internal static string Produto_ValorCompra {
            get {
                return ResourceManager.GetString("Produto_ValorCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo valor venda é obrigatório.
        /// </summary>
        internal static string Produto_ValorVenda {
            get {
                return ResourceManager.GetString("Produto_ValorVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário {0} não tem permissão de acesso a funcionalidade {1}.
        /// </summary>
        internal static string Usuario_AcessoNegado {
            get {
                return ResourceManager.GetString("Usuario_AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com o email informado.
        /// </summary>
        internal static string Usuario_CadastroDuplicado {
            get {
                return ResourceManager.GetString("Usuario_CadastroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não pode ser excluído pois está associado a um perfil ou já efetuou login no sistema.
        /// </summary>
        internal static string Usuario_CadastroUtilizado {
            get {
                return ResourceManager.GetString("Usuario_CadastroUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email é obrigatório.
        /// </summary>
        internal static string Usuario_Email {
            get {
                return ResourceManager.GetString("Usuario_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        internal static string Usuario_EmailInvalido {
            get {
                return ResourceManager.GetString("Usuario_EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluído com sucesso.
        /// </summary>
        internal static string Usuario_ExcluiUsuarioOK {
            get {
                return ResourceManager.GetString("Usuario_ExcluiUsuarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login expirado, faça a autenticação novamente.
        /// </summary>
        internal static string Usuario_LoginExpirado {
            get {
                return ResourceManager.GetString("Usuario_LoginExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        internal static string Usuario_NaoEncontrado {
            get {
                return ResourceManager.GetString("Usuario_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário autenticação.
        /// </summary>
        internal static string Usuario_NecessarioAutenticacao {
            get {
                return ResourceManager.GetString("Usuario_NecessarioAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        internal static string Usuario_Nome {
            get {
                return ResourceManager.GetString("Usuario_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nova senha é obrigatório.
        /// </summary>
        internal static string Usuario_NovaSenha {
            get {
                return ResourceManager.GetString("Usuario_NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo confirmação de nova senha é obrigatório.
        /// </summary>
        internal static string Usuario_NovaSenhaConfirmacao {
            get {
                return ResourceManager.GetString("Usuario_NovaSenhaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha gerada com sucesso.
        /// </summary>
        internal static string Usuario_NovaSenhaGeradaOK {
            get {
                return ResourceManager.GetString("Usuario_NovaSenhaGeradaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário salvo com sucesso.
        /// </summary>
        internal static string Usuario_SalvaUsuarioOK {
            get {
                return ResourceManager.GetString("Usuario_SalvaUsuarioOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha é obrigatório.
        /// </summary>
        internal static string Usuario_Senha {
            get {
                return ResourceManager.GetString("Usuario_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Alterada com sucesso.
        /// </summary>
        internal static string Usuario_SenhaAlteradaOK {
            get {
                return ResourceManager.GetString("Usuario_SenhaAlteradaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo confirmação de senha é obrigatório.
        /// </summary>
        internal static string Usuario_SenhaConfirmacao {
            get {
                return ResourceManager.GetString("Usuario_SenhaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo confirmação de senha é inválido.
        /// </summary>
        internal static string Usuario_SenhaConfirmacao_Incorreta {
            get {
                return ResourceManager.GetString("Usuario_SenhaConfirmacao_Incorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        internal static string Usuario_SenhaInvalida {
            get {
                return ResourceManager.GetString("Usuario_SenhaInvalida", resourceCulture);
            }
        }
    }
}
