//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabi.LeBibi.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabi.LeBibi.Model.Resource.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo assunto excedeu o limite.
        /// </summary>
        internal static string Email_AssuntoTamanho {
            get {
                return ResourceManager.GetString("Email_AssuntoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo email excedeu o limite.
        /// </summary>
        internal static string Email_CorpoTamanho {
            get {
                return ResourceManager.GetString("Email_CorpoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo destinatário excedeu o limite.
        /// </summary>
        internal static string Email_DestinatarioTamanho {
            get {
                return ResourceManager.GetString("Email_DestinatarioTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo nome excedeu o limite.
        /// </summary>
        internal static string Perfil_NomeTamanho {
            get {
                return ResourceManager.GetString("Perfil_NomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo descrição excedeu o limite.
        /// </summary>
        internal static string Produto_DescricaoTamanho {
            get {
                return ResourceManager.GetString("Produto_DescricaoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo email excedeu o limite.
        /// </summary>
        internal static string Usuario_EmailTamanho {
            get {
                return ResourceManager.GetString("Usuario_EmailTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo nome excedeu o limite.
        /// </summary>
        internal static string Usuario_NomeTamanho {
            get {
                return ResourceManager.GetString("Usuario_NomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo senha excedeu o limite.
        /// </summary>
        internal static string Usuario_SenhaTamanho {
            get {
                return ResourceManager.GetString("Usuario_SenhaTamanho", resourceCulture);
            }
        }
    }
}
